name: rooms
description: A command-line application that captures information from the questions asked to the user.
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

# dependencies:
#   args: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
